"""
Warning: This file is automatically generated by the following GIT hooks:
post-commit
post-checkout
post-receive
post-merge
post-update
push-to-checkout
push-to-deploy

It is in the repository but has attribute 'assume-unchanged'. It is specific for every worktree.
"""

version = 'v0.0.0-19-e1cb002__2023-12-03_10-01-30_-0600__master'